//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammersTest_Bell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billet
    {
        internal object nomDepartement;

        public int idBillet { get; set; }
        public string nomProjet { get; set; }
        public string description { get; set; }
        public int idDepartement { get; set; }
        public int idEmploye { get; set; }
    
        public virtual departement departement { get; set; }
        public virtual employe employe { get; set; }
    }
}
